# Generated by Django 4.0.2 on 2022-02-25 17:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_link', models.TextField()),
                ('short_link_suffix', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LinkUnshortening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('shortened_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unshortenings', to='url_short.shortenedlink')),
            ],
        ),
    ]
